### ISSUE TITLE
Exception getting image field for Type9

### ISSUE THREAD

**Issue by mgogolin** [ebts/jet#14]
Calling LogicalRecord.getImageField() on a Type 9 record throws:
`EbtsHandlingException: Field identifier DATA does not exist for record type:9`
This is caused because getImageField() looks for a mnemonic 'DATA' that does not exist in TagMap.properties for Type 9.

**Comment by adamday2** [comment]
There was a new block added to the data handing in a recent pull request that I believe is affecting this. I'll get a corrected version pushed soon.

**Comment by mgogolin** [comment]
In reading documentation on Type 9, it seems that the fields in that record can be vendor specific and there is nothing preventing one from being an image field.  The change made in #15 prevents reading the images in instances where Type 9 has an image.

**Comment by adamday2** [comment]
Which documentation are you referring to? ANSI-NIST ITL?

I would not anticipate the features to be image data, but rather text-based feature encodings. As they vendor specific, it is hard to tell.

In either case, the getImageData is intended to align with a field named "data" and to simplify the retrieval of such fields in image-specific records (e.g., Type 10). Since these are vendor-specific, we would not know where to look this up. 

Could you instead use `field.getData()` to return the data from the desired field?
